### ISSUE TITLE
Is Streaming Audio in the future for this shard?

### ISSUE THREAD

**Issue by HCLarsen** [mjago/play#1]
Just wondering if you're planning to add the ability to play streaming audio from one of the many internet radio stations out there.

**Comment by mjago** [comment]
Sonicri already does that https://github.com/mjago/sonicri . This was just a simple example of using ffmpeg in a process, but I guess it would be easy to add.

**Comment by HCLarsen** [comment]
Is sonicri only usable through that user interface, or does it have an API? I've got a future Crystal project where I'm going to want to integrate the ability to play internet radio.

**Comment by mjago** [comment]
I doubt there will ever be an API.
